### ISSUE TITLE
irからinsnへの修正漏れ

### ISSUE THREAD

**Issue by dsajgiouawj** [ourfool/poyo-v#1]
0ae221bc9d30765ad6e80449b1dadcd979225737 でdecoder.vの9行目がinsnに変更された時cpu_top.vの73行目がirのままになっているので　named port connection 'ir' does not exist for instance 'decoder_0' of module 'decoder' 　というエラーが出ます
なおcpu_top.vを修正して一度bitstreamの生成に成功した後再度irに戻してGenerate Bitstream を実行すると成功してしまいます

**Comment by ourfool** [comment]
ありがとうございます。
b5c1b94fc2e2874930dfeede2fa728ec94166a93 にて修正しました。
